### ISSUE TITLE
Error uploading fish data in RBIS

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2940]
The error log : 
```
2/12/2022 9:35:29 AMTraceback (most recent call last):
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
2/12/2022 9:35:29 AM    R = retval = fun(*args, **kwargs)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
2/12/2022 9:35:29 AM    return self.run(*args, **kwargs)
2/12/2022 9:35:29 AM  File "/usr/src/bims/bims/tasks/collections_upload.py", line 66, in collections_upload
2/12/2022 9:35:29 AM    uploader.start()
2/12/2022 9:35:29 AM  File "/usr/src/bims/bims/scripts/data_upload.py", line 46, in start
2/12/2022 9:35:29 AM    self.process_csv_dict_reader()
2/12/2022 9:35:29 AM  File "/usr/src/bims/bims/scripts/data_upload.py", line 208, in process_csv_dict_reader
2/12/2022 9:35:29 AM    self.process_row(row=row)
2/12/2022 9:35:29 AM  File "/usr/src/bims/bims/scripts/occurrences_upload.py", line 704, in process_row
2/12/2022 9:35:29 AM    self.process_data(row)
2/12/2022 9:35:29 AM  File "/usr/src/bims/bims/scripts/occurrences_upload.py", line 518, in process_data
2/12/2022 9:35:29 AM    _collector.save()
2/12/2022 9:35:29 AM  File "/usr/src/geonode/geonode/people/models.py", line 200, in save
2/12/2022 9:35:29 AM    super(Profile, self).save(*args, **kwargs)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
2/12/2022 9:35:29 AM    super().save(*args, **kwargs)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 744, in save
2/12/2022 9:35:29 AM    force_update=force_update, update_fields=update_fields)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 782, in save_base
2/12/2022 9:35:29 AM    force_update, using, update_fields,
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 854, in _save_table
2/12/2022 9:35:29 AM    forced_update)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 903, in _do_update
2/12/2022 9:35:29 AM    return filtered._update(values) > 0
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
2/12/2022 9:35:29 AM    return query.get_compiler(self.db).execute_sql(CURSOR)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1471, in execute_sql
2/12/2022 9:35:29 AM    cursor = super().execute_sql(result_type)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
2/12/2022 9:35:29 AM    cursor.execute(sql, params)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/raven/contrib/django/client.py", line 127, in execute
2/12/2022 9:35:29 AM    return real_execute(self, sql, params)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
2/12/2022 9:35:29 AM    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
2/12/2022 9:35:29 AM    return executor(sql, params, many, context)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2/12/2022 9:35:29 AM    return self.cursor.execute(sql, params)
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
2/12/2022 9:35:29 AM    raise dj_exc_value.with_traceback(traceback) from exc_value
2/12/2022 9:35:29 AM  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2/12/2022 9:35:29 AM    return self.cursor.execute(sql, params)
2/12/2022 9:35:29 AMdjango.db.utils.DataError: value too long for type character varying(255)
```

Increase the max_length for collector/owner institute field.

**Comment by mmindje** [comment]
Fish data were successfully uploaded- we had to reduce the longer texts. @dimasciput will work on the issue for the future
